#!/usr/bin/env python3
"""Refresh the static BMI Volksbegehren snapshot.

The BMI website (``bmi.gv.at``) sits behind Myra Cloud, which blocks
many cloud/VPS IP ranges (incl. Hetzner) — so the production server
cannot fetch this list directly. We therefore ship a static JSON
snapshot under ``data/volksbegehren.json`` and refresh it via this
script, run **locally** from a non-blocked IP (typical home network,
office, etc.) whenever a new Volksbegehren is held.

Usage (from backend/):
    python3 scripts/refresh_volksbegehren.py

The script writes ``data/volksbegehren.json`` and prints a short diff
(new/changed entries vs. the previous snapshot).  Commit + push the
updated JSON to roll it out.

Frequency: typically a couple of times per year — Volksbegehren are
held in batched Eintragungswochen.  Check ``bmi.gv.at/411/`` for
upcoming dates if you want to schedule the refresh.
"""

import asyncio
import json
import os
import sys
import time

import httpx

# Make sure we can import services.* when run from any cwd.
HERE = os.path.dirname(os.path.abspath(__file__))
BACKEND_ROOT = os.path.dirname(HERE)
sys.path.insert(0, BACKEND_ROOT)

from services.volksbegehren import (  # noqa: E402
    BMI_VBG_URL,
    STATIC_JSON_PATH,
    _BROWSER_HEADERS,
    _parse_table,
)


def _load_existing() -> dict:
    if not os.path.exists(STATIC_JSON_PATH):
        return {"entries": []}
    try:
        with open(STATIC_JSON_PATH, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {"entries": []}


def _entry_key(e: dict) -> tuple:
    return (e.get("jahr"), (e.get("betreff") or "")[:60])


async def main() -> int:
    print(f"Fetching {BMI_VBG_URL}...")
    async with httpx.AsyncClient(timeout=30.0, follow_redirects=False) as c:
        try:
            resp = await c.get(BMI_VBG_URL, headers=_BROWSER_HEADERS)
        except httpx.HTTPError as e:
            print(f"ERROR: HTTP error: {e}", file=sys.stderr)
            return 1

    if resp.status_code in (301, 302, 303, 307, 308):
        loc = resp.headers.get("location", "")
        print(
            f"ERROR: BMI redirected (HTTP {resp.status_code} → {loc[:80]}). "
            "This IP is likely blocked by Myra Cloud — try from a different "
            "network (home, office, mobile hotspot).",
            file=sys.stderr,
        )
        return 2
    if resp.status_code != 200:
        print(
            f"ERROR: BMI returned HTTP {resp.status_code}", file=sys.stderr
        )
        return 3

    print(f"  HTTP 200, {len(resp.text):,} bytes")
    entries = _parse_table(resp.text)
    if not entries:
        print("ERROR: parser returned 0 entries — page format changed?",
              file=sys.stderr)
        return 4

    existing = _load_existing()
    old_entries = existing.get("entries") or []
    old_keys = {_entry_key(e) for e in old_entries}
    new_keys = {_entry_key(e) for e in entries}

    added = new_keys - old_keys
    removed = old_keys - new_keys

    print(f"  parsed: {len(entries)} entries (was: {len(old_entries)})")
    if added:
        print(f"  + new entries ({len(added)}):")
        for k in sorted(added, key=lambda kv: -(kv[0] or 0)):
            print(f"      {k[0]}  {k[1]}")
    if removed:
        print(f"  - removed entries ({len(removed)}):")
        for k in sorted(removed, key=lambda kv: -(kv[0] or 0)):
            print(f"      {k[0]}  {k[1]}")
    if not added and not removed:
        print("  (no diff — content unchanged)")

    payload = {
        "entries": entries,
        "fetched_at_iso": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source_url": BMI_VBG_URL,
        "note": (
            "Generated by scripts/refresh_volksbegehren.py — primary source "
            "for production because BMI/Myra Cloud blocks Hetzner IPs."
        ),
    }
    with open(STATIC_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"  wrote {STATIC_JSON_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
